title: Meu projeto para estagio
description: Teste para estagio.
template:
  repo: meu-projeto-para-estagio-template
  name: meu-projeto-para-estagio
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
